# Generated by Django 5.1.4 on 2024-12-14 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sort_alter_product_sort'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sort',
        ),
    ]
